# config/packages/security.yaml

security:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: login

    firewalls:
        api:
            pattern: ^/api/
            stateless: true
            custom_authenticators:
                - App\Security\JwtAuthenticator

        main:
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: /logout

    access_control:
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        ROLE_VENDOR: [ROLE_USER]
